
abstract: Even Simpler Perl Module Compilation
author: Chia-liang Kao <clkao@clkao.org>
distribution_type: module
generated_by: Module::Install version 0.61
license: perl
name: Module-Compile-Simple
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.6.1
version: 0.24
